#+TITLE: Dot Doctor Code
This is my first attempt of doing literate programming, don't be to harsh. ;)

This document will go over the implementation of Dot Doctor. For me info about the project check =README.org=.

* Shebang & imports
#+begin_src python :tangle dotdoctor.py
#!/usr/bin/env python3
#+end_src
** Python
#+begin_src python :tangle dotdoctor.py
import os
from environ_helper import (env_exists, get_env)
from curses_helper import (init_color_pairs, draw_error_page)
from dotdata import DotData
#+end_src
** Curses
#+begin_src python :tangle dotdoctor.py
import curses
from curses import wrapper
#+end_src

* Helpers
** Environ Helper
#+begin_src python :tangle environ_helper.py
import os
from os import environ
#+end_src
*** Environmental variable exist
#+begin_src python :tangle environ_helper.py
def env_exists(name):
    return name in environ
#+end_src
*** Get environmental variable
#+begin_src python :tangle environ_helper.py
def get_env(name):
    return environ.get(name)
#+end_src
** Curses Helper
#+begin_src python :tangle curses_helper.py
import curses
#+end_src
*** Init Color Pairs
This method is used to set up additional color pairs for curses to use. By default only one color pair exists (0: white on black).
#+begin_src python :tangle curses_helper.py
def init_color_pairs():
    curses.init_pair(1, curses.COLOR_GREEN, curses.COLOR_BLACK)
    curses.init_pair(2, curses.COLOR_RED, curses.COLOR_BLACK)
    curses.init_pair(3, curses.COLOR_MAGENTA, curses.COLOR_BLACK)
#+end_src
*** Draw Error page
This is method is a quick and easy way to create error message.
#+begin_src python :tangle curses_helper.py
def draw_error_page(stdscr, header, message):
    stdscr.clear()
    stdscr.addstr(3, 3, header, curses.color_pair(2))
    stdscr.addstr(4, 3, message, curses.color_pair(3))
#+end_src

** DotData
To save my sanity I had to create class for storing all the relevant info about any given dot file.
#+begin_src python :tangle dotdata.py
class DotData:
    enabled = False
    def __init__(self, name, relative_path, status):
        self.name = name
        self.relative_path = relative_path
        self.status = status
    def set_status(self, status):
        self.status = status
#+end_src
* Init
** Checking variable
To locate directory with config files *dot doctor* uses environmental variable called =dotdoctor_dir=.
I guess at some point I could change this to variable stored in config file, but for the first version it will be more than enough.
#+begin_src python :tangle dotdoctor.py
def get_dotdoctor_dir_path():
    if env_exists("dotdoctor_dir"):
        global dotdoctor_dir
        dotdoctor_dir = get_env("dotdoctor_dir")
    else:
        wrapper(draw_env_missing_error)
def draw_env_missing_error(stdscr):
    init_color_pairs()
    header = "ERROR"
    message = "Environemntal variable $dotdoctor_dir is not set."
    draw_error_page(stdscr, header, message)
    stdscr.getkey()
#+end_src
** Check the dotdoctor_dir
Call me crazy but checking if the directory exits and has at least one file inside sounds like a good idea.
#+begin_src python :tangle dotdoctor.py
def validate_dotdoctor_dir():
    if os.path.exists(dotdoctor_dir) == False:
        wrapper(draw_dir_missing_error)
    if len(os.listdir(dotdoctor_dir)) == 0:
        wrapper(draw_dir_empty_error)
def draw_dir_missing_error(stdscr):
    init_color_pairs()
    header = "ERROR"
    message = "{} does not exist.".format(dotdoctor_dir)
    draw_error_page(stdscr, header, message)
    stdscr.getkey()
def draw_dir_empty_error(stdscr):
    init_color_pairs()
    header = "ERROR"
    message = "{} is empty.".format(dotdoctor_dir)
    draw_error_page(stdscr, header, message)
    stdscr.getkey()
#+end_src
** Create list of available files and directories
After everything is ready to go, application goes into dot files directory and creates list of directories and files inside. For now it will only go inside of =.config= directory, other directories will be treated similar to files.
#+begin_src python :tangle dotdoctor.py
def create_config_list():
    global config_list
    config_list = []
    files_list = os.listdir(dotdoctor_dir)
    for file in files_list:
        if file != ".config":
            config_list.append(DotData(file, file, False))
    if '.config' in os.listdir(dotdoctor_dir):
        path = os.path.join(dotdoctor_dir, ".config")
        files_list = os.listdir(path)
        for file in files_list:
            config_list.append(DotData(file, os.path.join(".config", file), False))

#+end_src
** Update list of enabled configs
After list of files and directories is done, dot doctor goes into home directory and check what files were replaced with symbolic links. If the symbolic link is present config is marked as enabled.
** Calling init methods
#+begin_src python :tangle dotdoctor.py
if __name__ == "__main__":
    get_dotdoctor_dir_path()
    validate_dotdoctor_dir()
    create_config_list()
    print(len(config_list))
#+end_src
